=== cp5113/ADSBPacketDelivery/src/xml/schema/ATSOL_TRAJECTORY_20190306_V6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.example.org/ATSOL_TRAJECTORY_20190306_V6" elementFormDefault="qualified" xmlns:p="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:SJ="http://www.example.org/ATSOL_TRAJECTORY_20190306_V6">

	<xsd:element name="ATSOL" type="SJ:Trajectory"></xsd:element>

	<xsd:complexType name="Trajectory">
		<xsd:sequence>
			<xsd:element name="AircraftXML" type="SJ:AircraftXMLType" maxOccurs="unbounded" minOccurs="1"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="AircraftXMLType">
		<xsd:sequence>
			<xsd:element name="Generator" type="xsd:string"
				maxOccurs="1" minOccurs="1">
			</xsd:element>
			<xsd:element name="Time" maxOccurs="1" minOccurs="1"
				type="xsd:dateTime">
			</xsd:element>
			<xsd:element name="Reg" type="xsd:string" maxOccurs="1"
				minOccurs="1">
			</xsd:element>
			<xsd:element name="Type" type="xsd:string" maxOccurs="1"
				minOccurs="1">
			</xsd:element>
			<xsd:element name="Latitude" type="xsd:double" maxOccurs="1"
				minOccurs="1">
			</xsd:element>
			<xsd:element name="Longitude" type="xsd:double"
				maxOccurs="1" minOccurs="1">
			</xsd:element>
			<xsd:element name="Altitude" type="xsd:int" maxOccurs="1"
				minOccurs="1">
			</xsd:element>
			<xsd:element name="GroundSpeed" type="xsd:int" maxOccurs="1"
				minOccurs="1">
			</xsd:element>
			<xsd:element name="LocationStatus"
				type="SJ:LocationStatusType" maxOccurs="1" minOccurs="1">
			</xsd:element>
			<xsd:element name="Callsign" type="xsd:string" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="Origination" maxOccurs="1"
				minOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="4"></xsd:length>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Destination" maxOccurs="1"
				minOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="4"></xsd:length>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="STD" type="xsd:dateTime" maxOccurs="1"
				minOccurs="1">
			</xsd:element>
			<xsd:element name="AOBT" type="xsd:dateTime" maxOccurs="1"
				minOccurs="1">
			</xsd:element>
			<xsd:element name="ETD" type="xsd:dateTime" maxOccurs="1"
				minOccurs="1">
			</xsd:element>
			<xsd:element name="ATOT" type="xsd:dateTime" maxOccurs="1"
				minOccurs="1">
			</xsd:element>
			<xsd:element name="STA" type="xsd:dateTime" maxOccurs="1"
				minOccurs="1">
			</xsd:element>
			<xsd:element name="ETA" type="xsd:dateTime" maxOccurs="1"
				minOccurs="1">
			</xsd:element>
			<xsd:element name="ALDT" type="xsd:dateTime" maxOccurs="1"
				minOccurs="1">
			</xsd:element>
			<xsd:element name="AIBT" type="xsd:dateTime" maxOccurs="1"
				minOccurs="1">
			</xsd:element>

			<xsd:element name="RouteAir" type="xsd:string" maxOccurs="1"
				minOccurs="0">
				<xsd:annotation></xsd:annotation>
			</xsd:element>
			<xsd:element name="RouteGround" type="xsd:string"
				maxOccurs="1" minOccurs="0">
			</xsd:element>
			<xsd:element name="RwyArr" type="xsd:string" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="RwyDep" type="xsd:string" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="STAR" type="xsd:string" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="IAP" type="xsd:string" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="SID" type="xsd:string" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="SpotArr" type="xsd:string" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="SpotLT" type="xsd:string" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="SpotDep" type="xsd:string" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="ETC" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

    <xsd:simpleType name="LocationStatusType">
    	<xsd:restriction base="xsd:string">
    		<xsd:enumeration value="OnGate"></xsd:enumeration>
    		<xsd:enumeration value="OnTaxiway"></xsd:enumeration>
    		<xsd:enumeration value="OnRunway"></xsd:enumeration>    		
    		<xsd:enumeration value="OnSID"></xsd:enumeration>
    		<xsd:enumeration value="OnSTAR"></xsd:enumeration>
    		<xsd:enumeration value="OnAPP"></xsd:enumeration>
    		<xsd:enumeration value="OnATS"></xsd:enumeration>
    		<xsd:enumeration value="InAirspace"></xsd:enumeration>
    		
    	</xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="TimeType">
    	<xsd:restriction base="xsd:string">
    		<xsd:length value="19"></xsd:length>
    	</xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== cp5113/ADSBPacketDelivery/src/xml/schema/ATSOL_TRAJECTORY_20190306_V6.xml
<?xml version="1.0" encoding="UTF-8"?>
<SJ:ATSOL xmlns:SJ="http://www.example.org/ATSOL_TRAJECTORY_20190306_V6" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ATSOL_TRAJECTORY_20190306_V6 ATSOL_TRAJECTORY_20190306_V6.xsd ">
  <SJ:AircraftXML>
    <SJ:Generator>SJ:Generator</SJ:Generator>
    <SJ:Time>2001-12-31T12:00:00</SJ:Time>
    <SJ:Reg>SJ:Reg</SJ:Reg>
    <SJ:Type>SJ:Type</SJ:Type>
    <SJ:Latitude>0.0</SJ:Latitude>
    <SJ:Longitude>0.0</SJ:Longitude>
    <SJ:Altitude>0</SJ:Altitude>
    <SJ:GroundSpeed>0</SJ:GroundSpeed>
    <SJ:LocationStatus>OnTaxiway</SJ:LocationStatus>
    <SJ:Callsign>SJ:Callsign</SJ:Callsign>
    <SJ:Origination>RKSI</SJ:Origination>
    <SJ:Destination>RKPC</SJ:Destination>
    <SJ:STD>2001-12-31T12:00:00</SJ:STD>
    <SJ:ETD>2001-12-31T12:00:00</SJ:ETD>
    <SJ:ATD>2001-12-31T12:00:00</SJ:ATD>
    <SJ:STA>2001-12-31T12:00:00</SJ:STA>
    <SJ:ETA>2001-12-31T12:00:00</SJ:ETA>
    <SJ:ATA>2001-12-31T12:00:00</SJ:ATA>
    <SJ:RouteAir>SJ:RouteAir</SJ:RouteAir>
    <SJ:RouteGround>SJ:RouteGround</SJ:RouteGround>
    <SJ:RwyArr>SJ:RwyArr</SJ:RwyArr>
    <SJ:RwyDep>SJ:RwyDep</SJ:RwyDep>
    <SJ:STAR>SJ:STAR</SJ:STAR>
    <SJ:IAP>SJ:IAP</SJ:IAP>
    <SJ:SID>SJ:SID</SJ:SID>
    <SJ:SpotArr>SJ:SpotArr</SJ:SpotArr>
    <SJ:SpotLT>SJ:SpotLT</SJ:SpotLT>
    <SJ:SpotDep>SJ:SpotDep</SJ:SpotDep>
    <SJ:ETC>SJ:ETC</SJ:ETC>
  </SJ:AircraftXML>
</SJ:ATSOL>
