=== cp5113/ADSBPacketDelivery/src/xml/schema/샘플xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="샘플xml" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="샘플xml">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="ID" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="GUID" type="9" value="mKvWv0Z+HUSyxGnQ5IyF5Q==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACYq9a/Rn4dRLLEadDkjIXlAAAAAD4uIUB8h+RAAAAAAAAAAADYwAzV
eABtAGwAAAAAAAAAwqVCiPG4y0m/CAScMho7zQcAAACYq9a/Rn4dRLLEadDkjIXl
dMeEuQAAAAAAAPd6UkbjTt9EkhtK86O4bgwHAAAAmKvWv0Z+HUSyxGnQ5IyF5fzI
jMEAAAAAAAAkjixKObjRTpVeUQl76yzhBwAAAJir1r9Gfh1EssRp0OSMheWYsHTH
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAFAAAAAAAAAAAAAAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="이름" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="GUID" type="9" value="wqVCiPG4y0m/CAScMho7zQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="주소" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="GUID" type="9" value="93pSRuNO30SSG0rzo7huDA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="나이" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="General Number"/>
<od:fieldProperty name="GUID" type="9" value="JI4sSjm40U6VXlEJe+ss4Q==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== cp5113/ADSBPacketDelivery/src/xml/schema/샘플xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="샘플xml.xsd" generated="2015-02-08T21:11:34">
<샘플xml>
<ID>1</ID>
<이름>홍길동1</이름>
<주소>서울 서대문구 가1</주소>
<나이>1</나이>
</샘플xml>
<샘플xml>
<ID>2</ID>
<이름>홍길동2</이름>
<주소>서울 서대문구 가2</주소>
<나이>2</나이>
</샘플xml>
<샘플xml>
<ID>3</ID>
<이름>홍길동3</이름>
<주소>서울 서대문구 가3</주소>
<나이>3</나이>
</샘플xml>
<샘플xml>
<ID>4</ID>
<이름>홍길동4</이름>
<주소>서울 서대문구 가4</주소>
<나이>4</나이>
</샘플xml>
<샘플xml>
<ID>5</ID>
<이름>홍길동5</이름>
<주소>서울 서대문구 가5</주소>
<나이>5</나이>
</샘플xml>
<샘플xml>
<ID>6</ID>
<이름>홍길동6</이름>
<주소>서울 서대문구 가6</주소>
<나이>6</나이>
</샘플xml>
<샘플xml>
<ID>7</ID>
<이름>홍길동7</이름>
<주소>서울 서대문구 가7</주소>
<나이>7</나이>
</샘플xml>
<샘플xml>
<ID>8</ID>
<이름>홍길동8</이름>
<주소>서울 서대문구 가8</주소>
<나이>8</나이>
</샘플xml>
<샘플xml>
<ID>9</ID>
<이름>홍길동9</이름>
<주소>서울 서대문구 가9</주소>
<나이>9</나이>
</샘플xml>
<샘플xml>
<ID>10</ID>
<이름>홍길동10</이름>
<주소>서울 서대문구 가10</주소>
<나이>10</나이>
</샘플xml>
<샘플xml>
<ID>11</ID>
<이름>홍길동11</이름>
<주소>서울 서대문구 가11</주소>
<나이>11</나이>
</샘플xml>
<샘플xml>
<ID>12</ID>
<이름>홍길동12</이름>
<주소>서울 서대문구 가12</주소>
<나이>12</나이>
</샘플xml>
<샘플xml>
<ID>13</ID>
<이름>홍길동13</이름>
<주소>서울 서대문구 가13</주소>
<나이>13</나이>
</샘플xml>
<샘플xml>
<ID>14</ID>
<이름>홍길동14</이름>
<주소>서울 서대문구 가14</주소>
<나이>14</나이>
</샘플xml>
<샘플xml>
<ID>15</ID>
<이름>홍길동15</이름>
<주소>서울 서대문구 가15</주소>
<나이>15</나이>
</샘플xml>
<샘플xml>
<ID>16</ID>
<이름>홍길동16</이름>
<주소>서울 서대문구 가16</주소>
<나이>16</나이>
</샘플xml>
<샘플xml>
<ID>17</ID>
<이름>홍길동17</이름>
<주소>서울 서대문구 가17</주소>
<나이>17</나이>
</샘플xml>
<샘플xml>
<ID>18</ID>
<이름>홍길동18</이름>
<주소>서울 서대문구 가18</주소>
<나이>18</나이>
</샘플xml>
<샘플xml>
<ID>19</ID>
<이름>홍길동19</이름>
<주소>서울 서대문구 가19</주소>
<나이>19</나이>
</샘플xml>
<샘플xml>
<ID>20</ID>
<이름>홍길동20</이름>
<주소>서울 서대문구 가20</주소>
<나이>20</나이>
</샘플xml>
<샘플xml>
<ID>21</ID>
<이름>홍길동21</이름>
<주소>서울 서대문구 가21</주소>
<나이>21</나이>
</샘플xml>
<샘플xml>
<ID>22</ID>
<이름>홍길동22</이름>
<주소>서울 서대문구 가22</주소>
<나이>22</나이>
</샘플xml>
<샘플xml>
<ID>23</ID>
<이름>홍길동23</이름>
<주소>서울 서대문구 가23</주소>
<나이>23</나이>
</샘플xml>
<샘플xml>
<ID>24</ID>
<이름>홍길동24</이름>
<주소>서울 서대문구 가24</주소>
<나이>24</나이>
</샘플xml>
</dataroot>
